<center>
  <h1 style="margin-bottom: 5px; font-weight:bold; font-size:40px;">Limpieza de Datos</h1>
  <hr style="width:50%; border:2px solid black; margin:10px;">
</center>

## **Libreria**

In [1]:
import numpy as np
import pandas as pd
import pyreadstat as py

<hr style="width:60%; border:1px solid; margin:20px 0 20px 0;">
<h1 style="margin:6px 0; font-weight:bold; font-size:30px;">Primera Encuesta de Polivictimización 2017</h1>
<hr style="width:60%; border:1px solid; margin:20px 0 20px 0;">

## ***- Lectura del archivo***

In [2]:
# Leemos el archivo SPSS (.sav)
resultado = py.read_sav("Base de datos - 1.sav")

df_1 = resultado[0]     # DataFrame
meta_1 = resultado[1]   # Metadata

In [3]:
df_1.head()

,fuente,folio,P1_1,P1_2,P1_3,P1_4,P1_5,P1_6,P1_7_1,P1_7_2,...,E2_una_en_vida,F_una_en_vida,A1_una_en_año,A2_una_en_año,B_una_en_año,C_una_en_año,D_una_en_año,E1_una_en_año,E2_una_en_año,F_una_en_año
0,Salida_10,10315.0,5.0,1.0,5.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,1.0
1,Salida_10,10418.0,1.0,1.0,1.0,1.0,13.0,8.0,1.0,NaN,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
2,Salida_10,10421.0,4.0,2.0,5.0,1.0,1.0,2.0,1.0,1.0,...,1.0,1.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0
3,Salida_10,10425.0,4.0,2.0,5.0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,1.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN
4,Salida_10,10426.0,4.0,2.0,6.0,1.0,1.0,1.0,1.0,1.0,...,2.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,1.0

## ***- Filtrado de los Datos***

In [4]:
# Columnas que queremos conservar
col_conservar_1 = [
    'region', 'comuna', 'P1_1', 'P1_2', 'P1_3',
    'PA_5', 'PA_5_1', 'PA_5_2', 'PA_5_3', 'PA_5_4',
    'PA_6', 'PA_6_1', 'PA_6_2', 'PA_6_3', 'PA_6_4',
    'PA_7', 'PA_7_1', 'PA_7_2', 'PA_7_3', 'PA_7_4', 'PA_7_5',
    
    'PB_1', 'PB_1_1', 'PB_1_2', 'PB_1_3', 'PB_1_4',
    'PB_2', 'PB_2_1', 'PB_2_2', 'PB_2_3', 'PB_2_4',
    
    'PC_1', 'PC_1_1', 'PC_1_2', 'PC_1_3',
    'PC_2', 'PC_2_1', 'PC_2_2', 'PC_2_3',
    'PC_3', 'PC_3_1', 'PC_3_2', 'PC_3_3',
    'PC_5', 'PC_5_1', 'PC_5_2', 'PC_5_3',

    'PD_1', 'PD_1_1', 'PD_1_2',
    'PD_3', 'PD_3_1', 'PD_3_2', 'PD_3_3', 'PD_3_4', 'PD_3_5',
    'PD_4', 'PD_4_1', 'PD_4_2', 'PD_4_3', 'PD_4_4',
    'PD_5', 'PD_5_1', 'PD_5_2', 'PD_5_3', 'PD_5_4',
    'PD_6', 'PD_6_1', 'PD_6_2', 'PD_6_3', 'PD_6_4', 'PD_6_5',
    'PD_7', 'PD_7_1', 'PD_7_2', 'PD_7_3', 'PD_7_4', 'PD_7_5', 'PD_7_6',

    'PG_1', 'PG_2', 'PG_3', 'PG_4', 'PG_6', 'PG_8', 'PG_9', 'PG_10',
]

In [5]:
# Filtramos por las columnas de interés
df_filtrado_1= df_1[col_conservar_1].copy()
df_filtrado_1.head()

,region,comuna,P1_1,P1_2,P1_3,PA_5,PA_5_1,PA_5_2,PA_5_3,PA_5_4,...,PD_7_5,PD_7_6,PG_1,PG_2,PG_3,PG_4,PG_6,PG_8,PG_9,PG_10
0,1.0,68.0,5.0,1.0,5.0,2.0,2.0,1.0,NaN,NaN,...,NaN,NaN,4.0,4.0,5.0,2.0,4.0,4.0,5.0,5.0
1,1.0,68.0,1.0,1.0,1.0,2.0,2.0,1.0,NaN,NaN,...,NaN,NaN,1.0,3.0,2.0,2.0,5.0,3.0,2.0,5.0
2,1.0,68.0,4.0,2.0,5.0,2.0,2.0,1.0,NaN,NaN,...,NaN,NaN,3.0,4.0,4.0,4.0,3.0,NaN,4.0,4.0
3,1.0,68.0,4.0,2.0,5.0,2.0,2.0,1.0,NaN,NaN,...,NaN,NaN,5.0,5.0,3.0,5.0,4.0,4.0,4.0,3.0
4,1.0,68.0,4.0,2.0,6.0,1.0,2.0,1.0,4.0,3.0,...,NaN,NaN,4.0,4.0,2.0,4.0,2.0,4.0,4.0,5.0

## ***- Limpieza de los Datos***

### **Valores Nulos**

In [6]:
df_filtrado_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19684 entries, 0 to 19683
Data columns (total 87 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   region  19684 non-null  float64
 1   comuna  19684 non-null  float64
 2   P1_1    19684 non-null  float64
 3   P1_2    19684 non-null  float64
 4   P1_3    19433 non-null  float64
 5   PA_5    19081 non-null  float64
 6   PA_5_1  19098 non-null  float64
 7   PA_5_2  19086 non-null  float64
 8   PA_5_3  2029 non-null   float64
 9   PA_5_4  2006 non-null   float64
 10  PA_6    19083 non-null  float64
 11  PA_6_1  19077 non-null  float64
 12  PA_6_2  19035 non-null  float64
 13  PA_6_3  9593 non-null   float64
 14  PA_6_4  9551 non-null   float64
 15  PA_7    19036 non-null  float64
 16  PA_7_1  19045 non-null  float64
 17  PA_7_2  19020 non-null  float64
 18  PA_7_3  3197 non-null   float64
 19  PA_7_4  3197 non-null   float64
 20  PA_7_5  3122 non-null   float64
 21  PB_1    19106 non-null  float64
 22  PB_1_1  19095 non-null  float64
 23  PB_1_2  19044 non-null  float64
 24  PB_1_3  6996 non-null   float64
 25  PB_1_4  5058 non-null   float64
 26  PB_2    19087 non-null  float64
 27  PB_2_1  19094 non-null  float64
 28  PB_2_2  19064 non-null  float64
 29  PB_2_3  5379 non-null   float64
 30  PB_2_4  5399 non-null   float64
 31  PC_1    19081 non-null  float64
 32  PC_1_1  19073 non-null  float64
 33  PC_1_2  19032 non-null  float64
 34  PC_1_3  7105 non-null   float64
 35  PC_2    18823 non-null  float64
 36  PC_2_1  18828 non-null  float64
 37  PC_2_2  18812 non-null  float64
 38  PC_2_3  1765 non-null   float64
 39  PC_3    19204 non-null  float64
 40  PC_3_1  19209 non-null  float64
 41  PC_3_2  19182 non-null  float64
 42  PC_3_3  6464 non-null   float64
 43  PC_5    18988 non-null  float64
 44  PC_5_1  19013 non-null  float64
 45  PC_5_2  18997 non-null  float64
 46  PC_5_3  759 non-null    float64
 47  PD_1    18950 non-null  float64
 48  PD_1_1  18955 non-null  float64
 49  PD_1_2  18922 non-null  float64
 50  PD_3    19029 non-null  float64
 51  PD_3_1  19048 non-null  float64
 52  PD_3_2  19038 non-null  float64
 53  PD_3_3  1059 non-null   float64
 54  PD_3_4  1084 non-null   float64
 55  PD_3_5  1086 non-null   float64
 56  PD_4    18984 non-null  float64
 57  PD_4_1  19002 non-null  float64
 58  PD_4_2  18993 non-null  float64
 59  PD_4_3  634 non-null    float64
 60  PD_4_4  651 non-null    float64
 61  PD_5    18910 non-null  float64
 62  PD_5_1  18940 non-null  float64
 63  PD_5_2  18933 non-null  float64
 64  PD_5_3  891 non-null    float64
 65  PD_5_4  915 non-null    float64
 66  PD_6    18995 non-null  float64
 67  PD_6_1  19005 non-null  float64
 68  PD_6_2  18998 non-null  float64
 69  PD_6_3  776 non-null    float64
 70  PD_6_4  792 non-null    float64
 71  PD_6_5  754 non-null    float64
 72  PD_7    18905 non-null  float64
 73  PD_7_1  18930 non-null  float64
 74  PD_7_2  18920 non-null  float64
 75  PD_7_3  482 non-null    float64
 76  PD_7_4  487 non-null    float64
 77  PD_7_5  491 non-null    float64
 78  PD_7_6  491 non-null    float64
 79  PG_1    19227 non-null  float64
 80  PG_2    19258 non-null  float64
 81  PG_3    19098 non-null  float64
 82  PG_4    19214 non-null  float64
 83  PG_6    19278 non-null  float64
 84  PG_8    19085 non-null  float64
 85  PG_9    19207 non-null  float64
 86  PG_10   19304 non-null  float64
dtypes: float64(87)
memory usage: 13.1 MB

Al revisar la cantidad de valores nulos en cada columna, se observa que varias presentan datos faltantes. Sin embargo, dado que se trata de respuestas de una encuesta, no es necesario eliminar estas filas ni asignar valores de manera arbitraria, ya que estos reflejan omisiones o decisiones de los encuestados de no responder. Por lo tanto, estos valores no representan errores en los datos, sino información válida sobre la falta de respuesta.

### **Renombramiento y agregación de columnas**

In [7]:
# Cambiamos el nombre de algunas columnas
df_filtrado_1.rename(columns={
    'region': 'Region_colegio',
    'comuna': 'Comuna_colegio',
    'P1_1': 'Curso_actual',
    'P1_2': 'Sexo',
    'P1_3': 'Edad'
}, inplace=True)

In [8]:
# Agregamos una columna que indica el año
df_filtrado_1["Año"] = 2017
df_filtrado_1.head()

,Region_colegio,Comuna_colegio,Curso_actual,Sexo,Edad,PA_5,PA_5_1,PA_5_2,PA_5_3,PA_5_4,...,PD_7_6,PG_1,PG_2,PG_3,PG_4,PG_6,PG_8,PG_9,PG_10,Año
0,1.0,68.0,5.0,1.0,5.0,2.0,2.0,1.0,NaN,NaN,...,NaN,4.0,4.0,5.0,2.0,4.0,4.0,5.0,5.0,2017
1,1.0,68.0,1.0,1.0,1.0,2.0,2.0,1.0,NaN,NaN,...,NaN,1.0,3.0,2.0,2.0,5.0,3.0,2.0,5.0,2017
2,1.0,68.0,4.0,2.0,5.0,2.0,2.0,1.0,NaN,NaN,...,NaN,3.0,4.0,4.0,4.0,3.0,NaN,4.0,4.0,2017
3,1.0,68.0,4.0,2.0,5.0,2.0,2.0,1.0,NaN,NaN,...,NaN,5.0,5.0,3.0,5.0,4.0,4.0,4.0,3.0,2017
4,1.0,68.0,4.0,2.0,6.0,1.0,2.0,1.0,4.0,3.0,...,NaN,4.0,4.0,2.0,4.0,2.0,4.0,4.0,5.0,2017

### **Conversión de tipos de datos**

In [9]:
# Identificamos todas las columnas de tipo float
cols_float = df_filtrado_1.select_dtypes(include='float').columns

# Reemplazamos los valores nulos por 0 (como no existen registros con valor 0, esto no altera la integridad de los datos)
df_filtrado_1[cols_float] = df_filtrado_1[cols_float].fillna(0)

# Convertimos los datos de tipo float a int 
df_filtrado_1[cols_float] = df_filtrado_1[cols_float].astype(int)

In [10]:
# Buscamos en qué label se encuentra la información del código - comuna
for key, val in meta_1.value_labels.items():
    if 'IQUIQUE' in str(val.values()):
        print(key)
        break

labels195

In [11]:
# Extraemos el diccionario de comunas
dicc_comunas = meta_1.value_labels['labels195']

# Reemplazamos los códigos por los nombres
df_filtrado_1['Comuna_colegio'] = df_filtrado_1['Comuna_colegio'].map(dicc_comunas)
df_filtrado_1

,Region_colegio,Comuna_colegio,Curso_actual,Sexo,Edad,PA_5,PA_5_1,PA_5_2,PA_5_3,PA_5_4,...,PD_7_6,PG_1,PG_2,PG_3,PG_4,PG_6,PG_8,PG_9,PG_10,Año
0,1,IQUIQUE,5,1,5,2,2,1,0,0,...,0,4,4,5,2,4,4,5,5,2017
1,1,IQUIQUE,1,1,1,2,2,1,0,0,...,0,1,3,2,2,5,3,2,5,2017
2,1,IQUIQUE,4,2,5,2,2,1,0,0,...,0,3,4,4,4,3,0,4,4,2017
3,1,IQUIQUE,4,2,5,2,2,1,0,0,...,0,5,5,3,5,4,4,4,3,2017
4,1,IQUIQUE,4,2,6,1,2,1,4,3,...,0,4,4,2,4,2,4,4,5,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19679,15,ARICA,4,1,6,2,2,1,0,0,...,0,5,5,1,5,5,5,1,1,2017
19680,15,ARICA,4,2,4,2,2,1,0,0,...,0,4,4,1,5,4,3,2,1,2017
19681,15,ARICA,4,2,4,2,2,1,0,0,...,0,4,4,3,5,4,4,4,3,2017
19682,15,ARICA,4,1,5,2,2,1,0,0,...,0,5,4,2,4,3,4,4,3,2017
19683,15,ARICA,3,1,4,2,2,1,0,0,...,0,4,4,3,4,4,4,2,2,2017

### ***---- META ----***

In [12]:
print(meta_1.variable_value_labels)

{'P1_1': {1.0: 'Séptimo Básico', 2.0: 'Octavo Básico', 3.0: 'Primero Medio', 4.0: 'Segundo Medio', 5.0: 'Tercero Medio'}, 'P1_2': {1.0: 'Mujer', 2.0: 'Hombre'}, 'P1_3': {1.0: '12 años', 2.0: '13 años', 3.0: '14 años', 4.0: '15 años', 5.0: '16 años', 6.0: '17 años', 7.0: '18 años', 8.0: '19 años o más'}, 'P1_4': {1.0: 'Chile', 2.0: 'Argentina', 3.0: 'Perú', 4.0: 'Bolivia', 5.0: 'Uruguay', 6.0: 'Brasil', 7.0: 'Colombia', 8.0: 'Haití', 9.0: 'República Dominicana', 10.0: 'Ecuador', 11.0: 'Venezuela', 12.0: 'Otro país', 13.0: 'No sé'}, 'P1_5': {1.0: 'Chile', 2.0: 'Argentina', 3.0: 'Perú', 4.0: 'Bolivia', 5.0: 'Uruguay', 6.0: 'Brasil', 7.0: 'Colombia', 8.0: 'Haití', 9.0: 'República Dominicana', 10.0: 'Ecuador', 11.0: 'Venezuela', 12.0: 'Otro país', 13.0: 'No sé'}, 'P1_6': {1.0: 'No pertenezco', 2.0: 'Aymara', 3.0: 'Quechua', 4.0: 'Atacameño', 5.0: 'Colla', 6.0: 'Diaguita', 7.0: 'Rapanui', 8.0: 'Mapuche', 9.0: 'Yagán', 10.0: 'Kawesqar', 11.0: 'Otro pueblo'}, 'P1_7_1': {1.0: 'Sí'}, 'P1_7_2': {1.0: 'Sí'}, 'P1_7_3': {1.0: 'Sí'}, 'P1_7_4': {1.0: 'Sí'}, 'P1_7_5': {1.0: 'Sí'}, 'P1_7_6': {1.0: 'Sí'}, 'P1_7_7': {1.0: 'Sí'}, 'P1_7_8': {1.0: 'Sí'}, 'P1_8_1': {1.0: 'Sí'}, 'P1_8_2': {1.0: 'Sí'}, 'P1_8_3': {1.0: 'Sí'}, 'P1_8_4': {1.0: 'Sí'}, 'P1_8_5': {1.0: 'Sí'}, 'P1_8_6': {1.0: 'Sí'}, 'PA_1': {1.0: 'Sí', 2.0: 'No'}, 'PA_1_1': {1.0: 'Sí', 2.0: 'No'}, 'PA_1_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PA_1_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PA_1_4': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña'}, 'PA_2': {1.0: 'Sí', 2.0: 'No'}, 'PA_2_1': {1.0: 'Sí', 2.0: 'No'}, 'PA_2_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PA_2_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PA_2_4': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña'}, 'PA_3': {1.0: 'Sí', 2.0: 'No'}, 'PA_3_1': {1.0: 'Sí', 2.0: 'No'}, 'PA_3_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PA_3_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PA_3_4': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña'}, 'PA_4': {1.0: 'Sí', 2.0: 'No'}, 'PA_4_1': {1.0: 'Sí', 2.0: 'No'}, 'PA_4_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PA_4_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PA_4_4': {1.0: 'Alguien cercano, que vive contigo', 2.0: 'Alguien cercano pero que no vive contigo', 3.0: 'Un extraño'}, 'PA_4_5': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña'}, 'PA_5': {1.0: 'Sí', 2.0: 'No'}, 'PA_5_1': {1.0: 'Sí', 2.0: 'No'}, 'PA_5_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PA_5_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PA_5_4': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña'}, 'PA_6': {1.0: 'Sí', 2.0: 'No'}, 'PA_6_1': {1.0: 'Sí', 2.0: 'No'}, 'PA_6_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PA_6_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PA_6_4': {1.0: 'Alguien cercano, que vive contigo', 2.0: 'Alguien cercano pero que no vive contigo', 3.0: 'Un extraño'}, 'PA_6_5': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña'}, 'PA_7': {1.0: 'Sí', 2.0: 'No'}, 'PA_7_1': {1.0: 'Sí', 2.0: 'No'}, 'PA_7_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PA_7_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PA_7_4': {1.0: 'Alguien cercano, que vive contigo', 2.0: 'Alguien cercano pero que no vive contigo', 3.0: 'Un extraño'}, 'PA_7_5': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña'}, 'PB_1': {1.0: 'Sí', 2.0: 'No'}, 'PB_1_1': {1.0: 'Sí', 2.0: 'No'}, 'PB_1_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PB_1_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PB_1_4': {1.0: 'Sí', 2.0: 'No'}, 'PB_2': {1.0: 'Sí', 2.0: 'No'}, 'PB_2_1': {1.0: 'Sí', 2.0: 'No'}, 'PB_2_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PB_2_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PB_2_4': {1.0: 'Sí', 2.0: 'No'}, 'PB_3': {1.0: 'Sí', 2.0: 'No'}, 'PB_3_1': {1.0: 'Sí', 2.0: 'No'}, 'PB_3_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PB_4': {1.0: 'Sí', 2.0: 'No'}, 'PB_4_1': {1.0: 'Sí', 2.0: 'No'}, 'PB_4_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PC_1': {1.0: 'Sí', 2.0: 'No'}, 'PC_1_1': {1.0: 'Sí', 2.0: 'No'}, 'PC_1_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PC_1_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PC_2': {1.0: 'Sí', 2.0: 'No'}, 'PC_2_1': {1.0: 'Sí', 2.0: 'No'}, 'PC_2_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PC_2_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PC_3': {1.0: 'Sí', 2.0: 'No'}, 'PC_3_1': {1.0: 'Sí', 2.0: 'No'}, 'PC_3_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PC_3_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PC_4': {1.0: 'Sí', 2.0: 'No'}, 'PC_4_1': {1.0: 'Sí', 2.0: 'No'}, 'PC_4_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PC_4_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PC_5': {1.0: 'Sí', 2.0: 'No'}, 'PC_5_1': {1.0: 'Sí', 2.0: 'No'}, 'PC_5_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PC_5_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PD_1': {1.0: 'Sí', 2.0: 'No'}, 'PD_1_1': {1.0: 'Sí', 2.0: 'No'}, 'PD_1_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PD_2': {1.0: 'Sí', 2.0: 'No'}, 'PD_2_1': {1.0: 'Sí', 2.0: 'No'}, 'PD_2_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PD_2_3': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña'}, 'PD_3': {1.0: 'Sí', 2.0: 'No'}, 'PD_3_1': {1.0: 'Sí', 2.0: 'No'}, 'PD_3_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PD_3_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PD_3_4': {1.0: 'Alguien cercano, que vive contigo', 2.0: 'Alguien cercano pero que no vive contigo', 3.0: 'Un extraño'}, 'PD_3_5': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña'}, 'PD_4': {1.0: 'Sí', 2.0: 'No'}, 'PD_4_1': {1.0: 'Sí', 2.0: 'No'}, 'PD_4_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PD_4_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PD_4_4': {1.0: 'Sí', 2.0: 'No'}, 'PD_5': {1.0: 'Sí', 2.0: 'No'}, 'PD_5_1': {1.0: 'Sí', 2.0: 'No'}, 'PD_5_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PD_5_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PD_5_4': {1.0: 'Sí', 2.0: 'No'}, 'PD_6': {1.0: 'Sí', 2.0: 'No'}, 'PD_6_1': {1.0: 'Sí', 2.0: 'No'}, 'PD_6_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PD_6_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PD_6_4': {1.0: 'Sí', 2.0: 'No'}, 'PD_6_5': {1.0: 'Sí', 2.0: 'No'}, 'PD_7': {1.0: 'Sí', 2.0: 'No'}, 'PD_7_1': {1.0: 'Sí', 2.0: 'No'}, 'PD_7_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PD_7_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PD_7_4': {1.0: 'Alguien cercano, que vive contigo', 2.0: 'Alguien cercano pero que no vive contigo', 3.0: 'Un extraño'}, 'PD_7_5': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña'}, 'PD_7_6': {1.0: 'Sí', 2.0: 'No'}, 'PE_1': {1.0: 'Sí', 2.0: 'No'}, 'PE_1_1': {1.0: 'Sí', 2.0: 'No'}, 'PE_1_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PE_2': {1.0: 'Sí', 2.0: 'No'}, 'PE_2_1': {1.0: 'Sí', 2.0: 'No'}, 'PE_2_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PE_2_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PE_3': {1.0: 'Sí', 2.0: 'No'}, 'PE_3_1': {1.0: 'Sí', 2.0: 'No'}, 'PE_3_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PE_3_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PE_4': {1.0: 'Sí', 2.0: 'No'}, 'PE_4_1': {1.0: 'Sí', 2.0: 'No'}, 'PE_4_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PE_4_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PE_5': {1.0: 'Sí', 2.0: 'No'}, 'PE_5_1': {1.0: 'Sí', 2.0: 'No'}, 'PE_5_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PE_5_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PE_6': {1.0: 'Sí', 2.0: 'No'}, 'PE_6_1': {1.0: 'Sí', 2.0: 'No'}, 'PE_6_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PE_6_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PE_6_4': {1.0: 'Sí', 2.0: 'No'}, 'PE_7': {1.0: 'Sí', 2.0: 'No'}, 'PE_7_1': {1.0: 'Sí', 2.0: 'No'}, 'PE_7_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PE_7_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle'}, 'PE_7_4': {1.0: 'Sí', 2.0: 'No'}, 'PF_1': {1.0: 'Sí', 2.0: 'No'}, 'PF_1_1': {1.0: 'Sí', 2.0: 'No'}, 'PF_1_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PF_1_3': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña', 5.0: 'No sé'}, 'PF_2': {1.0: 'Sí', 2.0: 'No'}, 'PF_2_1': {1.0: 'Sí', 2.0: 'No'}, 'PF_2_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días'}, 'PF_2_3': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña', 5.0: 'No sé'}, 'PG_1': {1.0: 'Muy en desacuerdo', 2.0: 'En desacuerdo', 3.0: 'Ni en acuerdo ni en desacuerdo', 4.0: 'De acuerdo', 5.0: 'Muy de acuerdo'}, 'PG_2': {1.0: 'Muy en desacuerdo', 2.0: 'En desacuerdo', 3.0: 'Ni en acuerdo ni en desacuerdo', 4.0: 'De acuerdo', 5.0: 'Muy de acuerdo'}, 'PG_3': {1.0: 'Muy en desacuerdo', 2.0: 'En desacuerdo', 3.0: 'Ni en acuerdo ni en desacuerdo', 4.0: 'De acuerdo', 5.0: 'Muy de acuerdo'}, 'PG_4': {1.0: 'Muy en desacuerdo', 2.0: 'En desacuerdo', 3.0: 'Ni en acuerdo ni en desacuerdo', 4.0: 'De acuerdo', 5.0: 'Muy de acuerdo'}, 'PG_5': {1.0: 'Muy en desacuerdo', 2.0: 'En desacuerdo', 3.0: 'Ni en acuerdo ni en desacuerdo', 4.0: 'De acuerdo', 5.0: 'Muy de acuerdo'}, 'PG_6': {1.0: 'Muy en desacuerdo', 2.0: 'En desacuerdo', 3.0: 'Ni en acuerdo ni en desacuerdo', 4.0: 'De acuerdo', 5.0: 'Muy de acuerdo'}, 'PG_7': {1.0: 'Muy en desacuerdo', 2.0: 'En desacuerdo', 3.0: 'Ni en acuerdo ni en desacuerdo', 4.0: 'De acuerdo', 5.0: 'Muy de acuerdo'}, 'PG_8': {1.0: 'Muy en desacuerdo', 2.0: 'En desacuerdo', 3.0: 'Ni en acuerdo ni en desacuerdo', 4.0: 'De acuerdo', 5.0: 'Muy de acuerdo'}, 'PG_9': {1.0: 'Muy en desacuerdo', 2.0: 'En desacuerdo', 3.0: 'Ni en acuerdo ni en desacuerdo', 4.0: 'De acuerdo', 5.0: 'Muy de acuerdo'}, 'PG_10': {1.0: 'Muy en desacuerdo', 2.0: 'En desacuerdo', 3.0: 'Ni en acuerdo ni en desacuerdo', 4.0: 'De acuerdo', 5.0: 'Muy de acuerdo'}, 'PH_1': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre'}, 'PH_2': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre'}, 'PH_3': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre'}, 'PH_4': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre'}, 'PH_5': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre'}, 'PH_6': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre'}, 'PH_7': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre'}, 'PH_8': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre'}, 'PH_9': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre'}, 'PH_10': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre'}, 'PH_11': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre'}, 'PH_12': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre'}, 'PH_13': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre'}, 'PH_14': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre'}, 'PH_15': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre'}, 'PH_16': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre'}, 'PH_17': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre'}, 'PH_18': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre'}, 'comuna': {1.0: 'AISEN', 2.0: 'ALGARROBO', 3.0: 'ALTO HOSPICIO', 4.0: 'ANCUD', 5.0: 'ANDACOLLO', 6.0: 'ANGOL', 7.0: 'ANTOFAGASTA', 8.0: 'ARAUCO', 9.0: 'ARICA', 10.0: 'BUIN', 11.0: 'BULNES', 12.0: 'CABRERO', 13.0: 'CALAMA', 14.0: 'CALBUCO', 15.0: 'CALDERA', 16.0: 'CALERA', 17.0: 'CALERA DE TANGO', 18.0: 'CAÑETE', 19.0: 'CARAHUE', 20.0: 'CASABLANCA', 21.0: 'CASTRO', 22.0: 'CATEMU', 23.0: 'CAUQUENES', 24.0: 'CERRILLOS', 25.0: 'CERRO NAVIA', 26.0: 'CHANCO', 27.0: 'CHEPICA', 28.0: 'CHIGUAYANTE', 29.0: 'CHILE CHICO', 30.0: 'CHILLAN', 31.0: 'CHILLAN VIEJO', 32.0: 'CHONCHI', 33.0: 'CISNES', 34.0: 'CODEGUA', 35.0: 'COELEMU', 36.0: 'COIHAIQUE', 37.0: 'COIHUECO', 38.0: 'COLINA', 39.0: 'CONCEPCION', 40.0: 'CONCHALI', 41.0: 'CONSTITUCION', 42.0: 'CONTULMO', 43.0: 'COPIAPO', 44.0: 'COQUIMBO', 45.0: 'CORONEL', 46.0: 'CUNCO', 47.0: 'CURACAUTIN', 48.0: 'CURACAVI', 49.0: 'CURANILAHUE', 50.0: 'CURICO', 51.0: 'DIEGO DE ALMAGRO', 52.0: 'EL BOSQUE', 53.0: 'EL MONTE', 54.0: 'ERCILLA', 55.0: 'ESTACION CENTRAL', 56.0: 'FLORIDA', 57.0: 'FREIRE', 58.0: 'FRESIA', 59.0: 'FUTRONO', 60.0: 'GORBEA', 61.0: 'GRANEROS', 62.0: 'HIJUELAS', 63.0: 'HUALAÑE', 64.0: 'HUALQUI', 65.0: 'HUECHURABA', 66.0: 'ILLAPEL', 67.0: 'INDEPENDENCIA', 68.0: 'IQUIQUE', 69.0: 'ISLA DE MAIPO', 70.0: 'LA CISTERNA', 71.0: 'LA CRUZ', 72.0: 'LA FLORIDA', 73.0: 'LA GRANJA', 74.0: 'LA LIGUA', 75.0: 'LA PINTANA', 76.0: 'LA REINA', 77.0: 'LA SERENA', 78.0: 'LA UNION', 79.0: 'LAJA', 80.0: 'LAMPA', 81.0: 'LANCO', 82.0: 'LAS CABRAS', 83.0: 'LAS CONDES', 84.0: 'LAUTARO', 85.0: 'LEBU', 86.0: 'LIMACHE', 87.0: 'LINARES', 88.0: 'LLAILLAY', 89.0: 'LLANQUIHUE', 90.0: 'LO ESPEJO', 91.0: 'LO PRADO', 92.0: 'LONCOCHE', 93.0: 'LONQUIMAY', 94.0: 'LOS ANDES', 95.0: 'LOS ANGELES', 96.0: 'LOS LAGOS', 97.0: 'LOS MUERMOS', 98.0: 'LOTA', 99.0: 'LUMACO', 100.0: 'MACUL', 101.0: 'MAIPU', 102.0: 'MARCHIHUE', 103.0: 'MARIQUINA', 104.0: 'MAULE', 105.0: 'MELIPILLA', 106.0: 'MOLINA', 107.0: 'MONTE PATRIA', 108.0: 'MULCHEN', 109.0: 'NACIMIENTO', 110.0: 'NANCAGUA', 111.0: 'NATALES', 112.0: 'ÑIQUEN', 113.0: 'NOGALES', 114.0: 'NUEVA IMPERIAL', 115.0: 'ÑUÑOA', 116.0: 'OSORNO', 117.0: 'OVALLE', 118.0: 'PADRE HURTADO', 119.0: 'PADRE LAS CASAS', 120.0: 'PAINE', 121.0: 'PANGUIPULLI', 122.0: 'PARRAL', 123.0: 'PEDRO AGUIRRE CERDA', 124.0: 'PELLUHUE', 125.0: 'PEÑAFLOR', 126.0: 'PEÑALOLEN', 127.0: 'PENCO', 128.0: 'PETORCA', 129.0: 'PIRQUE', 130.0: 'PITRUFQUEN', 131.0: 'PORVENIR', 132.0: 'PROVIDENCIA', 133.0: 'PUCON', 134.0: 'PUDAHUEL', 135.0: 'PUENTE ALTO', 136.0: 'PUERTO MONTT', 137.0: 'PUERTO OCTAY', 138.0: 'PUERTO VARAS', 139.0: 'PUNTA ARENAS', 140.0: 'PUTAENDO', 141.0: 'QUILICURA', 142.0: 'QUILLECO', 143.0: 'QUILLOTA', 144.0: 'QUILPUE', 145.0: 'QUINCHAO', 146.0: 'QUINTA NORMAL', 147.0: 'QUIRIHUE', 148.0: 'RANCAGUA', 149.0: 'RECOLETA', 150.0: 'RENCA', 151.0: 'RENGO', 152.0: 'RETIRO', 153.0: 'RIO NEGRO', 154.0: 'ROMERAL', 155.0: 'SAGRADA FAMILIA', 156.0: 'SALAMANCA', 157.0: 'SAN ANTONIO', 158.0: 'SAN BERNARDO', 159.0: 'SAN CARLOS', 160.0: 'SAN FABIAN', 161.0: 'SAN FELIPE', 162.0: 'SAN FERNANDO', 163.0: 'SAN JAVIER', 164.0: 'SAN JOAQUIN', 165.0: 'SAN MIGUEL', 166.0: 'SAN NICOLAS', 167.0: 'SAN PABLO', 168.0: 'SAN PEDRO DE LA PAZ', 169.0: 'SAN RAMON', 170.0: 'SAN VICENTE', 171.0: 'SANTA CRUZ', 172.0: 'SANTIAGO', 173.0: 'SANTO DOMINGO', 174.0: 'TALAGANTE', 175.0: 'TALCA', 176.0: 'TALCAHUANO', 177.0: 'TALTAL', 178.0: 'TEMUCO', 179.0: 'TOCOPILLA', 180.0: 'TOLTEN', 181.0: 'TOME', 182.0: 'TRAIGUEN', 183.0: 'VALDIVIA', 184.0: 'VALLENAR', 185.0: 'VALPARAISO', 186.0: 'VICUÑA', 187.0: 'VILCUN', 188.0: 'VILLA ALEMANA', 189.0: 'VILLARRICA', 190.0: 'VIÑA DEL MAR', 191.0

<hr style="width:60%; border:1px solid; margin:20px 0 20px 0;">
<h1 style="margin:6px 0; font-weight:bold; font-size:30px;">Segunda encuesta de Polivictimización 2023</h1>
<hr style="width:60%; border:1px solid; margin:20px 0 20px 0;">

## ***- Lectura del archivo***

In [13]:
# Leemos el archivo SPSS (.sav)
resultado = py.read_sav("Base de datos - 2.sav")

df_2 = resultado[0]     # Dataframe
meta_2 = resultado[1]   # Metadata

In [14]:
df_2.head()

,folio,rbd,dgv_rbd,nom_rbd,cod_reg_rbd,nom_com_rbd,cod_depe_estudio,region,macrozona,P1_1,...,poli_año,PG_autoestima,PH_depresion,edad_cat6,edad_cat3,wgt_alu,var_strat,var_unit,total,PH_depresion_dic
0,54099.0,10073.0,0.0,LICEO BICENTENARIO INDUSTRIAL VICENTE PEREZ RO...,13.0,QUINTA NORMAL,1.0,13.0,4.0,3.0,...,2.0,50.0,NaN,4.0,2.0,151.561317,113.0,10073.0,1.0,NaN
1,54099.0,10073.0,0.0,LICEO BICENTENARIO INDUSTRIAL VICENTE PEREZ RO...,13.0,QUINTA NORMAL,1.0,13.0,4.0,3.0,...,2.0,43.0,7.0,3.0,2.0,122.805397,113.0,10073.0,1.0,0.0
2,54099.0,10073.0,0.0,LICEO BICENTENARIO INDUSTRIAL VICENTE PEREZ RO...,13.0,QUINTA NORMAL,1.0,13.0,4.0,3.0,...,2.0,NaN,22.0,4.0,2.0,151.561317,113.0,10073.0,1.0,1.0
3,54099.0,10073.0,0.0,LICEO BICENTENARIO INDUSTRIAL VICENTE PEREZ RO...,13.0,QUINTA NORMAL,1.0,13.0,4.0,3.0,...,2.0,34.0,NaN,4.0,2.0,122.805397,113.0,10073.0,1.0,NaN
4,54099.0,10073.0,0.0,LICEO BICENTENARIO INDUSTRIAL VICENTE PEREZ RO...,13.0,QUINTA NORMAL,1.0,13.0,4.0,3.0,...,NaN,38.0,14.0,3.0,2.0,122.805397,113.0,10073.0,1.0,0.0

## ***- Filtrado de los Datos***

In [15]:
# Columnas que queremos conservar
col_conservar_2 = [
    'region', 'nom_com_rbd',
    'P1_1', 'P1_2', 'P1_3',
    
    'PA_5', 'PA_5_1', 'PA_5_2', 'PA_5_3', 'PA_5_4',
    'PA_6', 'PA_6_1', 'PA_6_2', 'PA_6_3', 'PA_6_4',
    'PA_7', 'PA_7_1', 'PA_7_2', 'PA_7_3', 'PA_7_4', 'PA_7_5',
    
    'PB_1', 'PB_1_1', 'PB_1_2', 'PB_1_3', 'PB_1_4',
    'PB_2', 'PB_2_1', 'PB_2_2', 'PB_2_3', 'PB_2_4',
    
    'PC_1', 'PC_1_1', 'PC_1_2', 'PC_1_3',
    'PC_2', 'PC_2_1', 'PC_2_2', 'PC_2_3',
    'PC_3', 'PC_3_1', 'PC_3_2', 'PC_3_3',
    'PC_5', 'PC_5_1', 'PC_5_2', 'PC_5_3',

    'PD_1', 'PD_1_1', 'PD_1_2',
    'PD_3', 'PD_3_1', 'PD_3_2', 'PD_3_3', 'PD_3_4', 'PD_3_5',
    'PD_4', 'PD_4_1', 'PD_4_2', 'PD_4_3', 'PD_4_4',
    'PD_5', 'PD_5_1', 'PD_5_2', 'PD_5_3', 'PD_5_4',
    'PD_6', 'PD_6_1', 'PD_6_2', 'PD_6_3', 'PD_6_4', 'PD_6_5',
    'PD_7', 'PD_7_1', 'PD_7_2', 'PD_7_3', 'PD_7_4', 'PD_7_5', 'PD_7_6',

    'PG_1', 'PG_2', 'PG_3', 'PG_4', 'PG_6', 'PG_8', 'PG_9', 'PG_10',
]

In [16]:
# Filtramos por las columnas de interés
df_filtrado_2 = df_2[col_conservar_2].copy()
df_filtrado_2.head()

,region,nom_com_rbd,P1_1,P1_2,P1_3,PA_5,PA_5_1,PA_5_2,PA_5_3,PA_5_4,...,PD_7_5,PD_7_6,PG_1,PG_2,PG_3,PG_4,PG_6,PG_8,PG_9,PG_10
0,13.0,QUINTA NORMAL,3.0,2.0,4.0,2.0,2.0,1.0,NaN,NaN,...,NaN,NaN,5.0,5.0,1.0,5.0,5.0,1.0,1.0,1.0
1,13.0,QUINTA NORMAL,3.0,1.0,3.0,2.0,2.0,1.0,NaN,NaN,...,NaN,NaN,4.0,4.0,1.0,4.0,4.0,1.0,1.0,1.0
2,13.0,QUINTA NORMAL,3.0,2.0,4.0,2.0,2.0,1.0,NaN,NaN,...,NaN,NaN,2.0,3.0,3.0,3.0,1.0,3.0,2.0,NaN
3,13.0,QUINTA NORMAL,3.0,1.0,4.0,2.0,2.0,1.0,NaN,NaN,...,NaN,NaN,4.0,5.0,3.0,4.0,5.0,3.0,5.0,4.0
4,13.0,QUINTA NORMAL,3.0,1.0,3.0,2.0,2.0,1.0,NaN,NaN,...,NaN,NaN,5.0,5.0,2.0,4.0,4.0,4.0,2.0,4.0

In [17]:
df_filtrado_2

,region,nom_com_rbd,P1_1,P1_2,P1_3,PA_5,PA_5_1,PA_5_2,PA_5_3,PA_5_4,...,PD_7_5,PD_7_6,PG_1,PG_2,PG_3,PG_4,PG_6,PG_8,PG_9,PG_10
0,13.0,QUINTA NORMAL,3.0,2.0,4.0,2.0,2.0,1.0,NaN,NaN,...,NaN,NaN,5.0,5.0,1.0,5.0,5.0,1.0,1.0,1.0
1,13.0,QUINTA NORMAL,3.0,1.0,3.0,2.0,2.0,1.0,NaN,NaN,...,NaN,NaN,4.0,4.0,1.0,4.0,4.0,1.0,1.0,1.0
2,13.0,QUINTA NORMAL,3.0,2.0,4.0,2.0,2.0,1.0,NaN,NaN,...,NaN,NaN,2.0,3.0,3.0,3.0,1.0,3.0,2.0,NaN
3,13.0,QUINTA NORMAL,3.0,1.0,4.0,2.0,2.0,1.0,NaN,NaN,...,NaN,NaN,4.0,5.0,3.0,4.0,5.0,3.0,5.0,4.0
4,13.0,QUINTA NORMAL,3.0,1.0,3.0,2.0,2.0,1.0,NaN,NaN,...,NaN,NaN,5.0,5.0,2.0,4.0,4.0,4.0,2.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13380,13.0,CONCHALÍ,4.0,2.0,4.0,2.0,2.0,1.0,NaN,NaN,...,NaN,NaN,2.0,2.0,4.0,2.0,2.0,3.0,4.0,4.0
13381,13.0,CONCHALÍ,4.0,2.0,4.0,2.0,2.0,1.0,NaN,NaN,...,NaN,NaN,5.0,4.0,3.0,4.0,3.0,4.0,4.0,4.0
13382,13.0,CONCHALÍ,4.0,2.0,4.0,1.0,2.0,1.0,2.0,4.0,...,NaN,NaN,2.0,3.0,5.0,3.0,1.0,4.0,5.0,5.0
13383,13.0,CONCHALÍ,4.0,2.0,4.0,1.0,1.0,2.0,4.0,1.0,...,NaN,NaN,4.0,4.0,5.0,4.0,4.0,4.0,4.0,4.0
13384,13.0,CONCHALÍ,4.0,2.0,6.0,2.0,2.0,1.0,NaN,NaN,...,NaN,NaN,5.0,5.0,2.0,5.0,4.0,5.0,4.0,4.0

## ***- Limpieza de los Datos***

### **Valores Nulos**

In [18]:
df_filtrado_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13385 entries, 0 to 13384
Data columns (total 87 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   region       13385 non-null  float64
 1   nom_com_rbd  13385 non-null  object
 2   P1_1         13243 non-null  float64
 3   P1_2         13351 non-null  float64
 4   P1_3         13159 non-null  float64
 5   PA_5         12808 non-null  float64
 6   PA_5_1       12853 non-null  float64
 7   PA_5_2       12828 non-null  float64
 8   PA_5_3       1378 non-null   float64
 9   PA_5_4       1342 non-null   float64
 10  PA_6         12810 non-null  float64
 11  PA_6_1       12829 non-null  float64
 12  PA_6_2       12772 non-null  float64
 13  PA_6_3       6594 non-null   float64
 14  PA_6_4       6530 non-null   float64
 15  PA_7         12776 non-null  float64
 16  PA_7_1       12803 non-null  float64
 17  PA_7_2       12767 non-null  float64
 18  PA_7_3       2631 non-null   float64
 19  PA_7_4       2606 non-null   float64
 20  PA_7_5       2507 non-null   float64
 21  PB_1         12859 non-null  float64
 22  PB_1_1       12866 non-null  float64
 23  PB_1_2       12805 non-null  float64
 24  PB_1_3       5014 non-null   float64
 25  PB_1_4       4290 non-null   float64
 26  PB_2         12839 non-null  float64
 27  PB_2_1       12848 non-null  float64
 28  PB_2_2       12815 non-null  float64
 29  PB_2_3       3352 non-null   float64
 30  PB_2_4       3385 non-null   float64
 31  PC_1         12822 non-null  float64
 32  PC_1_1       12835 non-null  float64
 33  PC_1_2       12791 non-null  float64
 34  PC_1_3       5439 non-null   float64
 35  PC_2         12610 non-null  float64
 36  PC_2_1       12637 non-null  float64
 37  PC_2_2       12615 non-null  float64
 38  PC_2_3       1433 non-null   float64
 39  PC_3         12930 non-null  float64
 40  PC_3_1       12916 non-null  float64
 41  PC_3_2       12876 non-null  float64
 42  PC_3_3       4957 non-null   float64
 43  PC_5         12725 non-null  float64
 44  PC_5_1       12747 non-null  float64
 45  PC_5_2       12732 non-null  float64
 46  PC_5_3       632 non-null    float64
 47  PD_1         12613 non-null  float64
 48  PD_1_1       12634 non-null  float64
 49  PD_1_2       12607 non-null  float64
 50  PD_3         12691 non-null  float64
 51  PD_3_1       12714 non-null  float64
 52  PD_3_2       12707 non-null  float64
 53  PD_3_3       845 non-null    float64
 54  PD_3_4       865 non-null    float64
 55  PD_3_5       860 non-null    float64
 56  PD_4         12708 non-null  float64
 57  PD_4_1       12723 non-null  float64
 58  PD_4_2       12717 non-null  float64
 59  PD_4_3       680 non-null    float64
 60  PD_4_4       686 non-null    float64
 61  PD_5         12607 non-null  float64
 62  PD_5_1       12633 non-null  float64
 63  PD_5_2       12626 non-null  float64
 64  PD_5_3       747 non-null    float64
 65  PD_5_4       759 non-null    float64
 66  PD_6         12677 non-null  float64
 67  PD_6_1       12695 non-null  float64
 68  PD_6_2       12688 non-null  float64
 69  PD_6_3       684 non-null    float64
 70  PD_6_4       705 non-null    float64
 71  PD_6_5       675 non-null    float64
 72  PD_7         12630 non-null  float64
 73  PD_7_1       12648 non-null  float64
 74  PD_7_2       12642 non-null  float64
 75  PD_7_3       585 non-null    float64
 76  PD_7_4       583 non-null    float64
 77  PD_7_5       588 non-null    float64
 78  PD_7_6       595 non-null    float64
 79  PG_1         12928 non-null  float64
 80  PG_2         12963 non-null  float64
 81  PG_3         12727 non-null  float64
 82  PG_4         12910 non-null  float64
 83  PG_6         12982 non-null  float64
 84  PG_8         12742 non-null  float64
 85  PG_9         12926 non-null  float64
 86  PG_10        13010 non-null  float64
dtypes: float64(86), object(1)
memory usage: 8.9+ MB

Al revisar la cantidad de valores nulos en cada columna, se observa que varias presentan datos faltantes. Sin embargo, dado que se trata de respuestas de una encuesta, no es necesario eliminar estas filas ni asignar valores de manera arbitraria, ya que estos reflejan omisiones o decisiones de los encuestados de no responder. Por lo tanto, estos valores no representan errores en los datos, sino información válida sobre la falta de respuesta.

### **Renombramiento y agregación de columnas**

In [19]:
# Cambiamos el nombre de algunas columnas
df_filtrado_2.rename(columns={
    'region': 'Region_colegio',
    'nom_com_rbd': 'Comuna_colegio',
    'P1_1': 'Curso_actual',
    'P1_2': 'Sexo',
    'P1_3': 'Edad'
}, inplace=True)

In [20]:
# Agregamos una columna que indica el año
df_filtrado_2["Año"] = 2023
df_filtrado_2.head()

,Region_colegio,Comuna_colegio,Curso_actual,Sexo,Edad,PA_5,PA_5_1,PA_5_2,PA_5_3,PA_5_4,...,PD_7_6,PG_1,PG_2,PG_3,PG_4,PG_6,PG_8,PG_9,PG_10,Año
0,13.0,QUINTA NORMAL,3.0,2.0,4.0,2.0,2.0,1.0,NaN,NaN,...,NaN,5.0,5.0,1.0,5.0,5.0,1.0,1.0,1.0,2023
1,13.0,QUINTA NORMAL,3.0,1.0,3.0,2.0,2.0,1.0,NaN,NaN,...,NaN,4.0,4.0,1.0,4.0,4.0,1.0,1.0,1.0,2023
2,13.0,QUINTA NORMAL,3.0,2.0,4.0,2.0,2.0,1.0,NaN,NaN,...,NaN,2.0,3.0,3.0,3.0,1.0,3.0,2.0,NaN,2023
3,13.0,QUINTA NORMAL,3.0,1.0,4.0,2.0,2.0,1.0,NaN,NaN,...,NaN,4.0,5.0,3.0,4.0,5.0,3.0,5.0,4.0,2023
4,13.0,QUINTA NORMAL,3.0,1.0,3.0,2.0,2.0,1.0,NaN,NaN,...,NaN,5.0,5.0,2.0,4.0,4.0,4.0,2.0,4.0,2023

### **Conversión de tipos de datos**

In [21]:
# Identificamos todas las columnas de tipo float
cols_float = df_filtrado_2.select_dtypes(include='float').columns

# Reemplazamos los valores nulos por 0 (como no existen registros con valor 0, esto no altera la integridad de los datos)
df_filtrado_2[cols_float] = df_filtrado_2[cols_float].fillna(0)

# Convertimos los datos de tipo float a int 
df_filtrado_2[cols_float] = df_filtrado_2[cols_float].astype(int)

In [22]:
df_filtrado_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13385 entries, 0 to 13384
Data columns (total 88 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Region_colegio  13385 non-null  int32
 1   Comuna_colegio  13385 non-null  object
 2   Curso_actual    13385 non-null  int32
 3   Sexo            13385 non-null  int32
 4   Edad            13385 non-null  int32
 5   PA_5            13385 non-null  int32
 6   PA_5_1          13385 non-null  int32
 7   PA_5_2          13385 non-null  int32
 8   PA_5_3          13385 non-null  int32
 9   PA_5_4          13385 non-null  int32
 10  PA_6            13385 non-null  int32
 11  PA_6_1          13385 non-null  int32
 12  PA_6_2          13385 non-null  int32
 13  PA_6_3          13385 non-null  int32
 14  PA_6_4          13385 non-null  int32
 15  PA_7            13385 non-null  int32
 16  PA_7_1          13385 non-null  int32
 17  PA_7_2          13385 non-null  int32
 18  PA_7_3          13385 non-null  int32
 19  PA_7_4          13385 non-null  int32
 20  PA_7_5          13385 non-null  int32
 21  PB_1            13385 non-null  int32
 22  PB_1_1          13385 non-null  int32
 23  PB_1_2          13385 non-null  int32
 24  PB_1_3          13385 non-null  int32
 25  PB_1_4          13385 non-null  int32
 26  PB_2            13385 non-null  int32
 27  PB_2_1          13385 non-null  int32
 28  PB_2_2          13385 non-null  int32
 29  PB_2_3          13385 non-null  int32
 30  PB_2_4          13385 non-null  int32
 31  PC_1            13385 non-null  int32
 32  PC_1_1          13385 non-null  int32
 33  PC_1_2          13385 non-null  int32
 34  PC_1_3          13385 non-null  int32
 35  PC_2            13385 non-null  int32
 36  PC_2_1          13385 non-null  int32
 37  PC_2_2          13385 non-null  int32
 38  PC_2_3          13385 non-null  int32
 39  PC_3            13385 non-null  int32
 40  PC_3_1          13385 non-null  int32
 41  PC_3_2          13385 non-null  int32
 42  PC_3_3          13385 non-null  int32
 43  PC_5            13385 non-null  int32
 44  PC_5_1          13385 non-null  int32
 45  PC_5_2          13385 non-null  int32
 46  PC_5_3          13385 non-null  int32
 47  PD_1            13385 non-null  int32
 48  PD_1_1          13385 non-null  int32
 49  PD_1_2          13385 non-null  int32
 50  PD_3            13385 non-null  int32
 51  PD_3_1          13385 non-null  int32
 52  PD_3_2          13385 non-null  int32
 53  PD_3_3          13385 non-null  int32
 54  PD_3_4          13385 non-null  int32
 55  PD_3_5          13385 non-null  int32
 56  PD_4            13385 non-null  int32
 57  PD_4_1          13385 non-null  int32
 58  PD_4_2          13385 non-null  int32
 59  PD_4_3          13385 non-null  int32
 60  PD_4_4          13385 non-null  int32
 61  PD_5            13385 non-null  int32
 62  PD_5_1          13385 non-null  int32
 63  PD_5_2          13385 non-null  int32
 64  PD_5_3          13385 non-null  int32
 65  PD_5_4          13385 non-null  int32
 66  PD_6            13385 non-null  int32
 67  PD_6_1          13385 non-null  int32
 68  PD_6_2          13385 non-null  int32
 69  PD_6_3          13385 non-null  int32
 70  PD_6_4          13385 non-null  int32
 71  PD_6_5          13385 non-null  int32
 72  PD_7            13385 non-null  int32
 73  PD_7_1          13385 non-null  int32
 74  PD_7_2          13385 non-null  int32
 75  PD_7_3          13385 non-null  int32
 76  PD_7_4          13385 non-null  int32
 77  PD_7_5          13385 non-null  int32
 78  PD_7_6          13385 non-null  int32
 79  PG_1            13385 non-null  int32
 80  PG_2            13385 non-null  int32
 81  PG_3            13385 non-null  int32
 82  PG_4            13385 non-null  int32
 83  PG_6            13385 non-null  int32
 84  PG_8            13385 non-null  int32
 85  PG_9            13385 non-null  int32
 86  PG_10           13385 non-null  int32
 87  Año             13385 non-null  int64
dtypes: int32(86), int64(1), object(1)
memory usage: 4.6+ MB

### **---- META ----**

In [23]:
print(meta_2.variable_value_labels)

{'cod_depe_estudio': {1.0: 'Municipal, AD, SLE', 2.0: 'Subvencionado', 3.0: 'Particular'}, 'region': {1.0: 'Tarapacá', 2.0: 'Antofagasta', 3.0: 'Atacama', 4.0: 'Coquimbo', 5.0: 'Valparaíso', 6.0: 'Rancagua', 7.0: 'Maule', 8.0: 'Biobío', 9.0: 'La Araucanía', 10.0: 'Los Lagos', 11.0: 'Aysén', 12.0: 'Magallanes', 13.0: 'Metropolitana', 14.0: 'Los Ríos', 15.0: 'Arica y Parinacota', 16.0: 'Ñuble'}, 'macrozona': {1.0: 'Norte', 2.0: 'Centro', 3.0: 'Sur', 4.0: 'Metropolitana'}, 'P1_1': {1.0: 'Séptimo Básico', 2.0: 'Octavo Básico', 3.0: 'Primero Medio', 4.0: 'Segundo Medio', 5.0: 'Tercero Medio'}, 'P1_2': {1.0: 'Hombre', 2.0: 'Mujer', 3.0: 'Otro'}, 'P1_3': {1.0: '12 años', 2.0: '13 años', 3.0: '14 años', 4.0: '15 años', 5.0: '16 años', 6.0: '17 años', 7.0: '18 años', 8.0: '19 años o más'}, 'P1_4': {1.0: 'Chile', 2.0: 'Argentina', 3.0: 'Perú', 4.0: 'Bolivia', 5.0: 'Uruguay', 6.0: 'Brasil', 7.0: 'Colombia', 8.0: 'Haití', 9.0: 'República Dominicana', 10.0: 'Ecuador', 11.0: 'Venezuela', 12.0: 'Otro país', 13.0: 'No sé', 99.0: 'Perdido'}, 'P1_5': {1.0: 'Chile', 2.0: 'Argentina', 3.0: 'Perú', 4.0: 'Bolivia', 5.0: 'Uruguay', 6.0: 'Brasil', 7.0: 'Colombia', 8.0: 'Haití', 9.0: 'República Dominicana', 10.0: 'Ecuador', 11.0: 'Venezuela', 12.0: 'Otro país', 13.0: 'No sé', 99.0: 'Perdido'}, 'P1_6': {1.0: 'No pertenezco', 2.0: 'Aymara', 3.0: 'Quechua', 4.0: 'Atacameño', 5.0: 'Colla', 6.0: 'Diaguita', 7.0: 'Rapanui', 8.0: 'Mapuche', 9.0: 'Yagán', 10.0: 'Kawesqar', 11.0: 'Otro pueblo', 99.0: 'Perdido'}, 'P1_7_1': {1.0: 'Sí', 99.0: 'Perdido'}, 'P1_7_2': {1.0: 'Sí', 99.0: 'Perdido'}, 'P1_7_3': {1.0: 'Sí', 99.0: 'Perdido'}, 'P1_7_4': {1.0: 'Sí', 99.0: 'Perdido'}, 'P1_7_5': {1.0: 'Sí', 99.0: 'Perdido'}, 'P1_7_6': {1.0: 'Sí', 99.0: 'Perdido'}, 'P1_7_7': {1.0: 'Sí', 99.0: 'Perdido'}, 'P1_7_8': {1.0: 'Sí', 99.0: 'Perdido'}, 'P1_8_1': {1.0: 'Sí', 99.0: 'Perdido'}, 'P1_8_2': {1.0: 'Sí', 99.0: 'Perdido'}, 'P1_8_3': {1.0: 'Sí', 99.0: 'Perdido'}, 'P1_8_4': {1.0: 'Sí', 99.0: 'Perdido'}, 'P1_8_5': {1.0: 'Sí', 99.0: 'Perdido'}, 'P1_8_6': {1.0: 'Sí', 99.0: 'Perdido'}, 'PA_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PA_1_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PA_1_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PA_1_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PA_1_4': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña', 99.0: 'Perdido'}, 'PA_2': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PA_2_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PA_2_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PA_2_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PA_2_4': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña', 99.0: 'Perdido'}, 'PA_3': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PA_3_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PA_3_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PA_3_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PA_3_4': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña', 99.0: 'Perdido'}, 'PA_4': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PA_4_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PA_4_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PA_4_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PA_4_4': {1.0: 'Alguien cercano, que vive contigo', 2.0: 'Alguien cercano pero que no vive contigo', 3.0: 'Un extraño', 99.0: 'Perdido'}, 'PA_4_5': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña', 99.0: 'Perdido'}, 'PA_5': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PA_5_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PA_5_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PA_5_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PA_5_4': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña', 99.0: 'Perdido'}, 'PA_6': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PA_6_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PA_6_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PA_6_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PA_6_4': {1.0: 'Alguien cercano, que vive contigo', 2.0: 'Alguien cercano pero que no vive contigo', 3.0: 'Un extraño', 99.0: 'Perdido'}, 'PA_6_5': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña', 99.0: 'Perdido'}, 'PA_7': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PA_7_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PA_7_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PA_7_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PA_7_4': {1.0: 'Alguien cercano, que vive contigo', 2.0: 'Alguien cercano pero que no vive contigo', 3.0: 'Un extraño', 99.0: 'Perdido'}, 'PA_7_5': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña', 99.0: 'Perdido'}, 'PB_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PB_1_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PB_1_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PB_1_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PB_1_4': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PB_2': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PB_2_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PB_2_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PB_2_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PB_2_4': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PB_3': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PB_3_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PB_3_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PB_4': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PB_4_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PB_4_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PC_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PC_1_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PC_1_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PC_1_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PC_2': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PC_2_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PC_2_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PC_2_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PC_3': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PC_3_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PC_3_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PC_3_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PC_4': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PC_4_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PC_4_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PC_4_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PC_5': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PC_5_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PC_5_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PC_5_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PD_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PD_1_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PD_1_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PD_1_3': {99.0: 'Perdido'}, 'PD_2': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PD_2_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PD_2_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PD_2_3': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña', 99.0: 'Perdido'}, 'PD_3': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PD_3_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PD_3_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PD_3_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PD_3_4': {1.0: 'Alguien cercano, que vive contigo', 2.0: 'Alguien cercano pero que no vive contigo', 3.0: 'Un extraño', 99.0: 'Perdido'}, 'PD_3_5': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña', 99.0: 'Perdido'}, 'PD_4': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PD_4_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PD_4_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PD_4_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PD_4_4': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PD_5': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PD_5_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PD_5_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PD_5_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PD_5_4': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PD_6': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PD_6_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PD_6_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PD_6_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PD_6_4': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PD_6_5': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PD_7': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PD_7_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PD_7_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PD_7_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PD_7_4': {1.0: 'Alguien cercano, que vive contigo', 2.0: 'Alguien cercano pero que no vive contigo', 3.0: 'Un extraño', 99.0: 'Perdido'}, 'PD_7_5': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña', 99.0: 'Perdido'}, 'PD_7_6': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PE_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PE_1_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PE_1_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PE_2': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PE_2_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PE_2_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PE_2_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PE_3': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PE_3_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PE_3_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PE_3_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PE_4': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PE_4_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PE_4_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PE_4_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PE_5': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PE_5_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PE_5_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PE_5_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PE_6': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PE_6_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PE_6_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PE_6_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PE_6_4': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PE_7': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PE_7_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PE_7_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PE_7_3': {1.0: 'Tu casa', 2.0: 'Colegio', 3.0: 'Cerca de tu casa, en tu barrio', 4.0: 'Lejos de tu casa, en algún lugar o en la calle', 99.0: 'Perdido'}, 'PE_7_4': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PF_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PF_1_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PF_1_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PF_1_3': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña', 5.0: 'No sé', 99.0: 'Perdido'}, 'PF_2': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PF_2_1': {1.0: 'Sí', 2.0: 'No', 99.0: 'Perdido'}, 'PF_2_2': {1.0: 'Nunca', 2.0: '1 vez', 3.0: '2 o 3 veces', 4.0: 'Al menos una vez al mes', 5.0: 'Al menos una vez a la semana', 6.0: 'Todos los días', 99.0: 'Perdido'}, 'PF_2_3': {1.0: 'Un adulto', 2.0: 'Una adulta', 3.0: 'Un adolescente o niño', 4.0: 'Una adolescente o niña', 5.0: 'No sé', 99.0: 'Perdido'}, 'PG_1': {1.0: 'Muy en desacuerdo', 2.0: 'En desacuerdo', 3.0: 'Ni en acuerdo ni en desacuerdo', 4.0: 'De acuerdo', 5.0: 'Muy de acuerdo', 99.0: 'Perdido'}, 'PG_2': {1.0: 'Muy en desacuerdo', 2.0: 'En desacuerdo', 3.0: 'Ni en acuerdo ni en desacuerdo', 4.0: 'De acuerdo', 5.0: 'Muy de acuerdo', 99.0: 'Perdido'}, 'PG_3': {1.0: 'Muy en desacuerdo', 2.0: 'En desacuerdo', 3.0: 'Ni en acuerdo ni en desacuerdo', 4.0: 'De acuerdo', 5.0: 'Muy de acuerdo', 99.0: 'Perdido'}, 'PG_4': {1.0: 'Muy en desacuerdo', 2.0: 'En desacuerdo', 3.0: 'Ni en acuerdo ni en desacuerdo', 4.0: 'De acuerdo', 5.0: 'Muy de acuerdo', 99.0: 'Perdido'}, 'PG_5': {1.0: 'Muy en desacuerdo', 2.0: 'En desacuerdo', 3.0: 'Ni en acuerdo ni en desacuerdo', 4.0: 'De acuerdo', 5.0: 'Muy de acuerdo', 99.0: 'Perdido'}, 'PG_6': {1.0: 'Muy en desacuerdo', 2.0: 'En desacuerdo', 3.0: 'Ni en acuerdo ni en desacuerdo', 4.0: 'De acuerdo', 5.0: 'Muy de acuerdo', 99.0: 'Perdido'}, 'PG_7': {1.0: 'Muy en desacuerdo', 2.0: 'En desacuerdo', 3.0: 'Ni en acuerdo ni en desacuerdo', 4.0: 'De acuerdo', 5.0: 'Muy de acuerdo', 99.0: 'Perdido'}, 'PG_8': {1.0: 'Muy en desacuerdo', 2.0: 'En desacuerdo', 3.0: 'Ni en acuerdo ni en desacuerdo', 4.0: 'De acuerdo', 5.0: 'Muy de acuerdo', 99.0: 'Perdido'}, 'PG_9': {1.0: 'Muy en desacuerdo', 2.0: 'En desacuerdo', 3.0: 'Ni en acuerdo ni en desacuerdo', 4.0: 'De acuerdo', 5.0: 'Muy de acuerdo', 99.0: 'Perdido'}, 'PG_10': {1.0: 'Muy en desacuerdo', 2.0: 'En desacuerdo', 3.0: 'Ni en acuerdo ni en desacuerdo', 4.0: 'De acuerdo', 5.0: 'Muy de acuerdo', 99.0: 'Perdido'}, 'PH_1': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre', 99.0: 'Perdido'}, 'PH_2': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre', 99.0: 'Perdido'}, 'PH_3': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre', 99.0: 'Perdido'}, 'PH_4': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre', 99.0: 'Perdido'}, 'PH_5': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre', 99.0: 'Perdido'}, 'PH_6': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre', 99.0: 'Perdido'}, 'PH_7': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre', 99.0: 'Perdido'}, 'PH_8': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre', 99.0: 'Perdido'}, 'PH_9': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre', 99.0: 'Perdido'}, 'PH_10': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre', 99.0: 'Perdido'}, 'PH_11': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre', 99.0: 'Perdido'}, 'PH_12': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre', 99.0: 'Perdido'}, 'PH_13': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre', 99.0: 'Perdido'}, 'PH_14': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre', 99.0: 'Perdido'}, 'PH_15': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre', 99.0: 'Perdido'}, 'PH_16': {1.0: 'Nunca', 2.0: 'A veces', 3.0: 'Siempre', 

<hr style="width:60%; border:1px solid; margin:20px 0 20px 0;">
<h1 style="margin:6px 0; font-weight:bold; font-size:30px;">Unión de DataFrames (2017 y 2023)</h1>
<hr style="width:60%; border:1px solid; margin:20px 0 20px 0;">

In [24]:
# Unimos ambos DataFrames resultantes de las encuestas de polivictimización
df_union = pd.concat([df_filtrado_1, df_filtrado_2], ignore_index=True)
df_union

,Region_colegio,Comuna_colegio,Curso_actual,Sexo,Edad,PA_5,PA_5_1,PA_5_2,PA_5_3,PA_5_4,...,PD_7_6,PG_1,PG_2,PG_3,PG_4,PG_6,PG_8,PG_9,PG_10,Año
0,1,IQUIQUE,5,1,5,2,2,1,0,0,...,0,4,4,5,2,4,4,5,5,2017
1,1,IQUIQUE,1,1,1,2,2,1,0,0,...,0,1,3,2,2,5,3,2,5,2017
2,1,IQUIQUE,4,2,5,2,2,1,0,0,...,0,3,4,4,4,3,0,4,4,2017
3,1,IQUIQUE,4,2,5,2,2,1,0,0,...,0,5,5,3,5,4,4,4,3,2017
4,1,IQUIQUE,4,2,6,1,2,1,4,3,...,0,4,4,2,4,2,4,4,5,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33064,13,CONCHALÍ,4,2,4,2,2,1,0,0,...,0,2,2,4,2,2,3,4,4,2023
33065,13,CONCHALÍ,4,2,4,2,2,1,0,0,...,0,5,4,3,4,3,4,4,4,2023
33066,13,CONCHALÍ,4,2,4,1,2,1,2,4,...,0,2,3,5,3,1,4,5,5,2023
33067,13,CONCHALÍ,4,2,4,1,1,2,4,1,...,0,4,4,5,4,4,4,4,4,2023
33068,13,CONCHALÍ,4,2,6,2,2,1,0,0,...,0,5,5,2,5,4,5,4,4,2023

### **Decodificasión de Códigos**

#### *- Regiones*

In [25]:
dicc_regiones = {
    1: "Tarapaca",
    2: "Antofagasta",
    3: "Atacama",
    4: "Coquimbo",
    5: "Valparaiso",
    6: "Rancagua",
    7: "Maule",
    8: "Biobio",
    9: "Araucania",
    10: "Los Lagos",
    11: "Aysen",
    12: "Magallanes",
    13: "Metropolitana",
    14: "Los Rios",
    15: "Arica y Parinacota",
    16: "Ñuble"
}

In [26]:
df_union['Region_colegio'] = df_union['Region_colegio'].map(dicc_regiones)

#### *- Cursos*

In [27]:
dicc_cursos = {
    1: 'Séptimo Básico',
    2: 'Octavo Básico',
    3: 'Primero Medio',
    4: 'Segundo Medio',
    5: 'Tercero Medio'
}

In [28]:
df_union['Curso_actual'] = df_union['Curso_actual'].map(dicc_cursos)

#### *- Edades*

In [29]:
dicc_edades = {
    1: '12',
    2: '13',
    3: '14',
    4: '15',
    5: '16',
    6: '17',
    7: '18',
    8: '19 o más'
}

In [30]:
df_union['Edad'] = df_union['Edad'].map(dicc_edades)

#### *- Sexo*

In [31]:
dicc_sexo = {
    1: 'Mujer',
    2: 'Hombre'
}

In [32]:
df_union['Sexo'] = df_union['Sexo'].map(dicc_sexo)

In [33]:
df_union

,Region_colegio,Comuna_colegio,Curso_actual,Sexo,Edad,PA_5,PA_5_1,PA_5_2,PA_5_3,PA_5_4,...,PD_7_6,PG_1,PG_2,PG_3,PG_4,PG_6,PG_8,PG_9,PG_10,Año
0,Tarapaca,IQUIQUE,Tercero Medio,Mujer,16,2,2,1,0,0,...,0,4,4,5,2,4,4,5,5,2017
1,Tarapaca,IQUIQUE,Séptimo Básico,Mujer,12,2,2,1,0,0,...,0,1,3,2,2,5,3,2,5,2017
2,Tarapaca,IQUIQUE,Segundo Medio,Hombre,16,2,2,1,0,0,...,0,3,4,4,4,3,0,4,4,2017
3,Tarapaca,IQUIQUE,Segundo Medio,Hombre,16,2,2,1,0,0,...,0,5,5,3,5,4,4,4,3,2017
4,Tarapaca,IQUIQUE,Segundo Medio,Hombre,17,1,2,1,4,3,...,0,4,4,2,4,2,4,4,5,2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33064,Metropolitana,CONCHALÍ,Segundo Medio,Hombre,15,2,2,1,0,0,...,0,2,2,4,2,2,3,4,4,2023
33065,Metropolitana,CONCHALÍ,Segundo Medio,Hombre,15,2,2,1,0,0,...,0,5,4,3,4,3,4,4,4,2023
33066,Metropolitana,CONCHALÍ,Segundo Medio,Hombre,15,1,2,1,2,4,...,0,2,3,5,3,1,4,5,5,2023
33067,Metropolitana,CONCHALÍ,Segundo Medio,Hombre,15,1,1,2,4,1,...,0,4,4,5,4,4,4,4,4,2023
33068,Metropolitana,CONCHALÍ,Segundo Medio,Hombre,17,2,2,1,0,0,...,0,5,5,2,5,4,5,4,4,2023

In [35]:
df_union.to_csv("Data-Encuestas", index=False, encoding="utf-8")

## **Bibliografía**
Reddit - lectura y paso de archvio sva  a csv: 
- https://www.reddit.com/r/learnpython/comments/1jj5t2s/how_to_convert_sav_file_into_csv_file/?tl=es-419